apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webapps.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: WebApp
    listKind: WebAppList
    plural: webapps
    singular: webapp
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            template_path:
              type: string
            image:
              type: string
            image_tag:
              type: string
            oauth_client_id:
              type: string
            openshift_host:
              type: string
            dc_name:
              type: string
